package org.mubasherusman.cms.views.caseform;

import com.vaadin.flow.component.Composite;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.button.ButtonVariant;
import com.vaadin.flow.component.datepicker.DatePicker;
import com.vaadin.flow.component.formlayout.FormLayout;
import com.vaadin.flow.component.html.H3;
import com.vaadin.flow.component.orderedlayout.FlexComponent.Alignment;
import com.vaadin.flow.component.orderedlayout.FlexComponent.JustifyContentMode;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.textfield.EmailField;
import com.vaadin.flow.component.textfield.TextField;
import com.vaadin.flow.router.Menu;
import com.vaadin.flow.router.PageTitle;
import com.vaadin.flow.router.Route;
import com.vaadin.flow.theme.lumo.LumoUtility.Gap;
import jakarta.annotation.security.RolesAllowed;

@PageTitle("Case Form")
@Menu(icon = "line-awesome/svg/user.svg", order = 4)
@Route(value = "case-form")
@RolesAllowed("ADMIN")
public class CaseFormView extends Composite<VerticalLayout> {

    public CaseFormView() {
        VerticalLayout layoutColumn2 = new VerticalLayout();
        H3 h3 = new H3();
        FormLayout formLayout2Col = new FormLayout();
        TextField textField = new TextField();
        TextField textField2 = new TextField();
        DatePicker datePicker = new DatePicker();
        TextField textField3 = new TextField();
        EmailField emailField = new EmailField();
        TextField textField4 = new TextField();
        VerticalLayout layoutColumn3 = new VerticalLayout();
        H3 h32 = new H3();
        FormLayout formLayout2Col2 = new FormLayout();
        TextField textField5 = new TextField();
        TextField textField6 = new TextField();
        DatePicker datePicker2 = new DatePicker();
        TextField textField7 = new TextField();
        EmailField emailField2 = new EmailField();
        TextField textField8 = new TextField();
        VerticalLayout layoutColumn4 = new VerticalLayout();
        H3 h33 = new H3();
        FormLayout formLayout2Col3 = new FormLayout();
        TextField textField9 = new TextField();
        TextField textField10 = new TextField();
        DatePicker datePicker3 = new DatePicker();
        TextField textField11 = new TextField();
        EmailField emailField3 = new EmailField();
        TextField textField12 = new TextField();
        HorizontalLayout layoutRow = new HorizontalLayout();
        Button buttonPrimary = new Button();
        Button buttonSecondary = new Button();
        getContent().setWidth("100%");
        getContent().getStyle().set("flex-grow", "1");
        getContent().setJustifyContentMode(JustifyContentMode.START);
        getContent().setAlignItems(Alignment.CENTER);
        layoutColumn2.setWidth("100%");
        layoutColumn2.setMaxWidth("800px");
        layoutColumn2.setHeight("min-content");
        h3.setText("Case Details");
        h3.setWidth("100%");
        formLayout2Col.setWidth("100%");
        textField.setLabel("First Name");
        textField2.setLabel("Last Name");
        datePicker.setLabel("Birthday");
        textField3.setLabel("Phone Number");
        emailField.setLabel("Email");
        textField4.setLabel("Occupation");
        layoutColumn3.setWidth("100%");
        layoutColumn3.setMaxWidth("800px");
        layoutColumn3.setHeight("min-content");
        h32.setText("Plaintiff Details");
        h32.setWidth("100%");
        formLayout2Col2.setWidth("100%");
        textField5.setLabel("First Name");
        textField6.setLabel("Last Name");
        datePicker2.setLabel("Birthday");
        textField7.setLabel("Phone Number");
        emailField2.setLabel("Email");
        textField8.setLabel("Occupation");
        layoutColumn4.setWidth("100%");
        layoutColumn4.setMaxWidth("800px");
        layoutColumn4.setHeight("min-content");
        h33.setText("Defendant Details");
        h33.setWidth("100%");
        formLayout2Col3.setWidth("100%");
        textField9.setLabel("First Name");
        textField10.setLabel("Last Name");
        datePicker3.setLabel("Birthday");
        textField11.setLabel("Phone Number");
        emailField3.setLabel("Email");
        textField12.setLabel("Occupation");
        layoutRow.addClassName(Gap.MEDIUM);
        layoutRow.setWidth("100%");
        layoutRow.getStyle().set("flex-grow", "1");
        buttonPrimary.setText("Save");
        buttonPrimary.setWidth("min-content");
        buttonPrimary.addThemeVariants(ButtonVariant.LUMO_PRIMARY);
        buttonSecondary.setText("Cancel");
        buttonSecondary.setWidth("min-content");
        getContent().add(layoutColumn2);
        layoutColumn2.add(h3);
        layoutColumn2.add(formLayout2Col);
        formLayout2Col.add(textField);
        formLayout2Col.add(textField2);
        formLayout2Col.add(datePicker);
        formLayout2Col.add(textField3);
        formLayout2Col.add(emailField);
        formLayout2Col.add(textField4);
        getContent().add(layoutColumn3);
        layoutColumn3.add(h32);
        layoutColumn3.add(formLayout2Col2);
        formLayout2Col2.add(textField5);
        formLayout2Col2.add(textField6);
        formLayout2Col2.add(datePicker2);
        formLayout2Col2.add(textField7);
        formLayout2Col2.add(emailField2);
        formLayout2Col2.add(textField8);
        getContent().add(layoutColumn4);
        layoutColumn4.add(h33);
        layoutColumn4.add(formLayout2Col3);
        formLayout2Col3.add(textField9);
        formLayout2Col3.add(textField10);
        formLayout2Col3.add(datePicker3);
        formLayout2Col3.add(textField11);
        formLayout2Col3.add(emailField3);
        formLayout2Col3.add(textField12);
        layoutColumn4.add(layoutRow);
        layoutRow.add(buttonPrimary);
        layoutRow.add(buttonSecondary);
    }
}
